services:
  - type: web
    name: nucleo-erp
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn ERP.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
